plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gaolou.haptictone'
    compileSdk 34

    defaultConfig {
        applicationId "com.gaolou.haptictone"
        minSdk 31
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        disable 'HardcodedText', 'LockedOrientationActivity'
        abortOnError false
    }
}
